# Generated by Django 4.1.5 on 2023-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=2, verbose_name=-1.1),
            preserve_default=False,
        ),
    ]
