# Generated by Django 4.1.5 on 2023-01-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_price_book_pric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pric',
            new_name='price',
        ),
    ]
